<a href="https://colab.research.google.com/github/Demon-Sheriff/Linear-Alg_ML_fs/blob/master/Naive_bayes_for_Blog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class NaiveBayes():

  def __init__(self):

    self.class_priors = {} # the class priors (0 -> ham, 1 -> spam)
    self.vocab_size = None # number of features OR number of unique words in the vocabulary
    self.spam_likelihoods = None # feature probabilities for spam class
    self.ham_likelihoods = None # feature probabilities for ham class

  def fit(self, X_train, y_train, alpha=1.0):

    """ Train Naive Bayes with Laplace Smoothing """
    X_train = np.array(X_train)
    y_train = np.array(y_train)
    n_samples ,self.vocab_size = X_train.shape # number of training examples, number of unique words.

    # optimal parameter calculation ⬇️

    # compute the class priors
    spam_count = y_train.sum()
    ham_count = n_samples - spam_count
    self.class_priors[1] = np.log(spam_count / n_samples)  # p(spam)
    self.class_priors[0] = np.log(ham_count / n_samples)  # p(ham)

    # compute the feature probabilities with Laplace smoothing (alpha represents the smoothing parameter)
    spam_word_count = X_train[y_train == 1].sum(axis=0) + alpha
    ham_word_count = X_train[y_train == 0].sum(axis=0) + alpha
    total_spam_words = spam_word_count.sum() + self.vocab_size * alpha
    total_ham_words = ham_word_count.sum() + self.vocab_size * alpha

    self.log_spam_likelihoods = np.log(spam_word_count / total_spam_words)
    self.log_ham_likelihoods = np.log(ham_word_count / total_ham_words)

  def predict(self, X_test):

    """ Predict class labels for input samples """
    X_test = np.array(X_test)

    log_prob_spam = self.class_priors[1] + X_test @ self.log_spam_likelihoods.T
    log_prob_ham = self.class_priors[0] + X_test @ self.log_ham_likelihoods.T

    # Predict spam if log_prob_spam > log_prob_ham
    return (log_prob_spam > log_prob_ham).astype(int)

In [ ]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = [1,1,0]
y = np.array(y)

In [ ]:
y == 1

array([ True,  True, False])

In [ ]:
X[y == 1]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
X[y == 1].sum(axis=0) + 1

array([ 6,  8, 10])

In [ ]:
y.sum()

2

In [ ]:
(X[y == 1] + 1) / y.sum() + 2

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [ ]:
import numpy as np

class NaiveBayes():

  def __init__(self):

    self.class_priors = {} # the class priors (0 -> ham, 1 -> spam)
    self.vocab_size = None # number of features OR number of unique words in the vocabulary
    self.spam_likelihood = {} # feature probability for spam class
    self.ham_likelihood = {} # feature probability for ham class

  def fit(self, X_train, y_train, alpha=1.0):

    """ Train Naive Bayes with Laplace Smoothing """
    X_train = np.array(X_train)
    y_train = np.array(y_train)
    n_samples ,self.vocab_size = X_train.shape # number of training examples, number of unique words.

    # optimal parameter calculation ⬇️

    # compute the class priors
    spam_count = y_train.sum()
    ham_count = n_samples - spam_count
    self.class_priors[1] = np.log(spam_count / n_samples) # p(spam)
    self.class_priors[0] = np.log(ham_count / n_samples) # p(ham)

    # compute the feature probabilities with Laplace smoothing (alpha represents the smoothing parameter)
    spam_word_count = X_train[y_train == 1].sum(axis=0) + alpha
    ham_word_count = X_train[y_train == 0].sum(axis=0) + alpha
    total_spam_words = spam_word_count.sum() + self.vocab_size * alpha
    total_ham_words = ham_word_count.sum() + self.vocab_size * alpha

    self.log_spam_likelihoods = np.log(spam_word_count / total_spam_words)
    self.log_ham_likelihoods = np.log(ham_word_count / total_ham_words)


  def predict(self, X_test):

    """ Predict class labels for input samples """
    X_test = np.array(X_test)

    log_prob_spam = self.class_priors[1] + X_test @ self.log_spam_likelihoods.T
    log_prob_ham = self.class_priors[0] + X_test @ self.log_ham_likelihoods.T

    # Predict spam if log_prob_spam > log_prob_ham
    return (log_prob_spam > log_prob_ham).astype(int)

In [ ]:
from sklearn.datasets import fetch_openml

In [ ]:
spambase = fetch_openml('spambase', version=1, as_frame=True)

In [ ]:
print(spambase)

{'data':       word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.00               0.64           0.64           0.0   
1               0.21               0.28           0.50           0.0   
2               0.06               0.00           0.71           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4596            0.31               0.00           0.62           0.0   
4597            0.00               0.00           0.00           0.0   
4598            0.30               0.00           0.30           0.0   
4599            0.96               0.00           0.00           0.0   
4600            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.32            0.00              

In [ ]:
X, y = spambase.data, spambase.target

In [ ]:
X

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.00               0.64           0.64           0.0   
1               0.21               0.28           0.50           0.0   
2               0.06               0.00           0.71           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4596            0.31               0.00           0.62           0.0   
4597            0.00               0.00           0.00           0.0   
4598            0.30               0.00           0.30           0.0   
4599            0.96               0.00           0.00           0.0   
4600            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.32            0.00              0.00                0.00   
1              0.14            0.28              0.21                0.07   
2              1.23            0.19              0.19                0.12   
3              0.63            0.00              0.31                0.63   
4              0.63            0.00              0.31                0.63   
...             ...             ...               ...                 ...   
4596           0.00            0.31              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.00            0.00              0.00                0.00   
4599           0.32            0.00              0.00                0.00   
4600           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  word_freq_conference  \
0                0.00            0.00  ...                   0.0   
1                0.00            0.94  ...                   0.0   
2                0.64            0.25  ...                   0.0   
3                0.31            0.63  ...                   0.0   
4                0.31            0.63  ...                   0.0   
...               ...             ...  ...                   ...   
4596             0.00            0.00  ...                   0.0   
4597             0.00            0.00  ...                   0.0   
4598             0.00            0.00  ...                   0.0   
4599             0.00            0.00  ...                   0.0   
4600             0.00            0.00  ...                   0.0   

      char_freq_%3B  char_freq_%28  char_freq_%5B  char_freq_%21  \
0             0.000          0.000            0.0          0.778   
1             0.000          0.132            0.0          0.372   
2             0.010          0.143            0.0          0.276   
3             0.000          0.137            0.0          0.137   
4             0.000          0.135            0.0          0.135   
...             ...            ...            ...            ...   
4596          0.000          0.232            0.0          0.000   
4597          0.000          0.000            0.0          0.353   
4598          0.102          0.718            0.0          0.000   
4599          0.000          0.057            0.0          0.000   
4600          0.000          0.000            0.0          0.125   

      char_freq_%24  char_freq_%23  capital_run_length_average  \
0             0.000          0.000                       3.756   
1             0.180          0.048                       5.114   
2             0.184          0.010                       9.821   
3             0.000          0.000                       3.537   
4             0.000          0.000                       3.537   
...             ...            ...                         ...   
4596          0.000          0.000                       1.142   
4597          0.000          0.000                    

In [ ]:
import pandas as pd

In [ ]:
import kagglehub

path = kagglehub.dataset_download("venky73/spam-mails-dataset")
print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/venky73/spam-mails-dataset/versions/1


In [ ]:
import os
data = pd.read_csv(os.path.join(path, "spam_ham_dataset.csv"))

In [ ]:
data.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [ ]:
data[data['label_num'] == 0].shape[0], data[data['label_num'] == 1].shape[0]

(3672, 1499)

In [ ]:
import re # Regular expressions for text cleaning (removing special characters, numbers, etc.)
import nltk # Natural Language Toolkit for text processing tasks
from nltk.corpus import stopwords # Stopwords list to remove common words like "the", "and", etc.
from nltk.tokenize import word_tokenize # Tokenization to split text into words
from nltk.stem import WordNetLemmatizer # Lemmatization to reduce words to their base form
from sklearn.feature_extraction.text import CountVectorizer  # Converts text into a bag-of-words representation`

In [ ]:
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [ ]:
def preprocess_text(text):
    # 1. Lowercasing
    text = text.lower()

    # 2. Remove special characters, numbers & stopwords
    text = re.sub(r'[^a-z\s]', '', text)  # Remove special characters & numbers
    words = word_tokenize(text)  # Tokenization
    words = [word for word in words if word not in stop_words]  # Remove stopwords

    # 3. Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    return ' '.join(words)

In [ ]:
data['clean_text'] = data['text'].apply(preprocess_text)

In [ ]:
data.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num', 'clean_text'], dtype='object')

In [ ]:
data.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num                                         clean_text  
0          0  subject enron methanol meter follow note gave ...  
1          0  subject hpl nom january see attached file hpln...  
2          0  subject neon retreat ho ho ho around wonderful...  
3          1  subject photoshop window office cheap main tre...  
4          0  subject indian spring deal book teco pvr reven...

In [ ]:
clean_data = data.drop(columns=['text', 'Unnamed: 0', 'label'])

In [ ]:
clean_data.head()

label_num                                         clean_text
0          0  subject enron methanol meter follow note gave ...
1          0  subject hpl nom january see attached file hpln...
2          0  subject neon retreat ho ho ho around wonderful...
3          1  subject photoshop window office cheap main tre...
4          0  subject indian spring deal book teco pvr reven...

In [ ]:
clean_data['label_num'].value_counts()

label_num
0    3672
1    1499
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train_text, X_test_text, y_train, y_test = train_test_split(clean_data['clean_text'], clean_data['label_num'], test_size=0.2, random_state=42)

In [ ]:
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train_text)  # Learn vocabulary from training set

In [ ]:
X_test = vectorizer.transform(X_test_text)

In [ ]:
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print("Feature Names:", vectorizer.get_feature_names_out())  # Check vocabulary
print("========================================================================================================================")
print("Vectorized Data:\n", X_train.toarray())  # See transformed data
print("========================================================================================================================")
print("Vocabulary:", vectorizer.vocabulary_)  # Shows learned words

Feature Names: ['aa' 'aaa' 'aabda' ... 'zzo' 'zzocb' 'zzsyt']
Vectorized Data:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Vocabulary: {'subject': 33017, 'april': 1906, 'activity': 391, 'survey': 33290, 'starting': 32625, 'collect': 7209, 'data': 9107, 'attached': 2435, 'drive': 10912, 'cost': 8203, 'commercial': 7342, 'team': 33801, 'please': 26717, 'select': 30922, 'rcs': 28588, 'fill': 13484, 'driver': 10916, 'quantity': 28213, 'requested': 29267, 'month': 23156, 'february': 13251, 'number': 24463, 'rc': 28579, 'end': 11953, 'day': 9149, 'thursday': 34298, 'may': 22038, 'th': 34084, 'group': 15559, 'currently': 8769, 'generates': 14759, 'standard': 32589, 'report': 29223, 'capture': 5604, 'surveyed': 33291, 'send': 30972, 'put': 27927, 'recipient': 28726, 'list': 20885, 'beginning': 3395, 'next': 24005, 'eliminate': 11698, 'need': 23840, 'every': 12597, 'would': 37688, 'like': 20782, 'information': 17990, '

In [ ]:
custom_clf = NaiveBayes()

In [ ]:
y_train

5132    0
2067    1
4716    0
4710    0
2268    1
       ..
4426    0
466     0
3092    1
3772    0
860     0
Name: label_num, Length: 4136, dtype: int64

In [ ]:
custom_clf.fit(X_train.toarray(), y_train)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y_pred = custom_clf.predict(X_test.toarray())

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
y_test

1566    0
1988    1
1235    0
2868    0
4903    0
       ..
1175    1
4476    0
4198    1
2689    0
2142    0
Name: label_num, Length: 1035, dtype: int64

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       742
           1       0.97      0.94      0.95       293

    accuracy                           0.97      1035
   macro avg       0.97      0.96      0.97      1035
weighted avg       0.97      0.97      0.97      1035



In [ ]:
from collections import Counter
print("Class distribution before SMOTE:", Counter(y_train))

Class distribution before SMOTE: Counter({0: 2930, 1: 1206})


In [ ]:
y_train.value_counts()

label_num
0    2930
1    1206
Name: count, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE


In [ ]:
# apply smote resampling to balance the classes
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train.toarray(), y_train)

In [ ]:
# check the class distribution
print("Class distribution after SMOTE:", Counter(y_train_resampled))

Class distribution after SMOTE: Counter({0: 2930, 1: 2930})


In [ ]:
new_clf = NaiveBayes()

In [ ]:
new_clf.fit(X_train_resampled, y_train_resampled)

In [ ]:
y_pred_new = new_clf.predict(X_test.toarray())

In [ ]:
print(classification_report(y_test, y_pred_new))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       742
           1       0.96      0.96      0.96       293

    accuracy                           0.98      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.98      0.98      0.98      1035



In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
sk_clf = MultinomialNB()

In [ ]:
sk_clf.fit(X_train_resampled, y_train_resampled)

MultinomialNB()

In [ ]:
y_pred_sk = sk_clf.predict(X_test.toarray())

In [ ]:
print(classification_report(y_test, y_pred_sk))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       742
           1       0.95      0.96      0.96       293

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035

